### ISSUE TITLE
Can you share the neural network code?

### ISSUE THREAD

**Issue by refaev** [Alpkant/Thermal-to-Visible-Face-Recognition-Using-Deep-Autoencoders#1]
Can you please share the neural network code?
And preferably, with the trained weights.

**Comment by Alpkant** [comment]
I will try to refactor and provide the model architecture codes which is written in PyTorch. I think trained weights will not be available.

**Comment by refaev** [comment]
Thanks.

**Comment by Alpkant** [comment]
I have added the model file and dataset loaders. Unfortunately, I can't upload the model weights.
