### ISSUE TITLE
5 images don't have annotations

### ISSUE THREAD

**Issue by caoxingdong** [Alpkant/Thermal-to-Visible-Face-Recognition-Using-Deep-Autoencoders#2]
Thanks so much for the manual annotations, but I found 5 images don't have annotations.

https://github.com/Alpkant/Thermal-to-Visible-Face-Recognition-Using-Deep-Autoencoders/blob/master/Landmark%20Annotations/Carl_annotations/16.xml

line 102 - line 111. If you need, I can help with these 5 images

**Comment by Alpkant** [comment]
Thank you so much for the findings. We have annotated all the images but probably I had a mistake while converting the labels to xml format. I am uploading these 5 labels. If you find more missing annotations please write to this issue.

**Comment by caoxingdong** [comment]
Some strange annotations:

https://github.com/Alpkant/Thermal-to-Visible-Face-Recognition-Using-Deep-Autoencoders/blob/master/Landmark%20Annotations/Carl_annotations/04.xml

line 301: 	image file="04/session_4/classic/04S4BNA3 - Copy.bmp"

https://github.com/Alpkant/Thermal-to-Visible-Face-Recognition-Using-Deep-Autoencoders/blob/master/Landmark%20Annotations/Carl_annotations/29.xml

line 257, 832 why these 2 images have 2 boxes?

Also another question: where is your box information from? I can see you manually annotate 6 facial landmark positions for each image, but how you get the box from the landmark positions? Or do you use some other ways? 

Thanks.

**Comment by caoxingdong** [comment]
2 images don't have annotations:

https://github.com/Alpkant/Thermal-to-Visible-Face-Recognition-Using-Deep-Autoencoders/blob/master/Landmark%20Annotations/Carl_annotations/16.xml

line 246 259 thanks

**Comment by Alpkant** [comment]
> 
> 
> Some strange annotations:
> 
> https://github.com/Alpkant/Thermal-to-Visible-Face-Recognition-Using-Deep-Autoencoders/blob/master/Landmark%20Annotations/Carl_annotations/04.xml
> 
> line 301: image file="04/session_4/classic/04S4BNA3 - Copy.bmp"
> 
> https://github.com/Alpkant/Thermal-to-Visible-Face-Recognition-Using-Deep-Autoencoders/blob/master/Landmark%20Annotations/Carl_annotations/29.xml
> 
> line 257, 832 why these 2 images have 2 boxes?
> 
> Also another question: where is your box information from? I can see you manually annotate 6 facial landmark positions for each image, but how you get the box from the landmark positions? Or do you use some other ways?
> 
> Thanks.

Box information is also a manually annotated face bounding box. It should contain the whole face but it may not include whole head. 2 boxes are generally mistakes, i will remove them. Only one box contains eye and mouth annotation for an image.

Thank you very much for finding these mistakes. I will fix them.
